name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ build-essential

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
