- name: Generate Coverage Report
      run: |
        sudo apt-get install -y lcov
        cd build
        cmake -DCMAKE_BUILD_TYPE=Coverage ..
        cmake --build .
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --list coverage.info

- name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        files: ./build/coverage.info

- name: Static Analysis
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --suppress=missingIncludeSystem .

- name: Check Format
      run: |
        sudo apt-get install -y clang-format
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run --Werror
