name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log Environment Details
      run: |
        uname -a
        g++ --version
        cmake --version

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++-12 build-essential

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cd build
        cmake -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer" -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Debug

    - name: Run Tests Sequentially
      env:
        ASAN_OPTIONS: "detect_leaks=1"
      run: |
        cd build
        ctest --output-on-failure --schedule-random=0

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: linux-test-results
        path: build/Testing/Temporary

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log Environment Details
      run: |
        uname -a
        clang --version
        cmake --version

    - name: Install Dependencies
      run: |
        brew install cmake

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g" \
              -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Debug

    - name: Run Tests Sequentially
      env:
        ASAN_OPTIONS: "detect_leaks=1 log_path=/tmp/asan-macos.log"
      run: |
        cd build
        ctest --output-on-failure --schedule-random=0 || true
        ls -l /tmp/asan-macos.log || echo "No ASan log found."
        cat /tmp/asan-macos.log || echo "ASan log is empty or missing."

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: macos-test-results
        path: |
          /tmp/asan-macos.log
          build/Testing/Temporary
