name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        asan_flags: ["-fsanitize=address -fno-omit-frame-pointer", ""]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Log System Information
      run: |
        echo "System Information:"
        uname -a
        echo "G++ Version:"
        g++ --version
        echo "CMake Version:"
        cmake --version

    - name: Install dependencies
      run: |
        if [[ "$(uname -s)" == "Darwin" ]]; then
          echo "Installing dependencies on macOS"
          brew install cmake
        else
          echo "Installing dependencies on Linux"
          sudo apt-get update
          sudo apt-get install -y cmake g++-12 build-essential
        fi

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      run: |
        cd build
        echo "Running CMake configuration..."
        if [[ "$(uname -s)" == "Darwin" ]]; then
          cmake -DCMAKE_BUILD_TYPE=Debug ..
        else
          cmake -DCMAKE_CXX_FLAGS="${{ matrix.asan_flags }}" -DCMAKE_BUILD
